spring:
  application:
    name: winter_vaction_checkin
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/activity?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.winter_vacation_check-in.domain
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 1234